### ISSUE TITLE
Order Depth displayed buggy when working with local backtester

### ISSUE THREAD

**Issue by Luka-R-Lukacevic** [jmerle/imc-prosperity-2-visualizer#1]
[1712044214.463666_a1dc682f-a3bb-4198-8576-08b7b436d26c.log](https://github.com/jmerle/imc-prosperity-2-visualizer/files/14833354/1712044214.463666_a1dc682f-a3bb-4198-8576-08b7b436d26c.log)

Hello there!

After utilizing a local backtester that also mimics the logs produced in the format needed for download I find that everything works fine except for the order depths displays. To reproduce the error you should just be able to upload the log, scroll a bit in time to the right (maybe two 20000 or so) and the order depths look like a mess!

![image](https://github.com/jmerle/imc-prosperity-2-visualizer/assets/125273166/9ccad53d-2a86-4604-8e8a-d4f3cc7acd56)

I checked the order books that he trades on and they look fine. Also the logs look fine to me, but I also dont understand from which part of the log he takes that information.

Best,
Luka

**Comment by jmerle** [comment]
Fixed in 5434d07086116893180273fbc1f514d484d7c248, thanks for reporting the issue and attaching a log file that reproduces it!

You may have a bug in your backtester though, I'm not sure whether it should be possible to have open bid and ask orders at the same price (see the STARFRUIT table below). I certainly don't remember seeing that in logs generated by Prosperity's submission environment:
![](https://github.com/jmerle/imc-prosperity-2-visualizer/assets/14951909/947987f2-f937-4557-9d4e-34d09b7d9071)
