### ISSUE TITLE
Adding estimated price to graphs

### ISSUE THREAD

**Issue by stevenshinechen** [jmerle/imc-prosperity-2-visualizer#4]
<img width="702" alt="image" src="https://github.com/jmerle/imc-prosperity-2-visualizer/assets/62472947/62cdc23b-b6fa-4999-a240-db1a8aba2073">

Currently, the visualizer only uses shows bid, asks and mid price.
But it would be helpful if we could a method could be added to be able to inject our own price into the visualizer so we can see how our predicted price matches with the product's prices.

**Comment by jmerle** [comment]
A similar request was posted on Discord a few days ago, I'll repost [my answer](https://discord.com/channels/1001852729725046804/1047409574090641439/1227327711886708789) because it's still the same:
![](https://github.com/jmerle/imc-prosperity-2-visualizer/assets/14951909/6ddceb7d-6222-4911-b46a-7cb285ca44ec)
